### ISSUE TITLE
Error with alpha chenel

### ISSUE THREAD

**Issue by Taruu** [AUTOMATIC1111/stable-diffusion-webui-pixelization#30]
I revive
`Pytorch RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0` 

in postprocessing_pixelization.py
need add `pp.image = pp.image.convert('RGB')`
after `pp.resize`

How to fix find there:
https://stackoverflow.com/questions/58496858/pytorch-runtimeerror-the-size-of-tensor-a-4-must-match-the-size-of-tensor-b

**Comment by demiguelm** [comment]
Is that a fix for this? https://github.com/AUTOMATIC1111/stable-diffusion-webui-pixelization/issues/32

**Comment by Taruu** [comment]
> Is that a fix for this? #32

Yes. This problem fixed in this [commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui-pixelization/commit/870584a568f3665d8ac6f72de5c97b60f35c38e9) 
You need make git pull or update ext from UI

**Comment by Taruu** [comment]
fixed in this [commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui-pixelization/commit/870584a568f3665d8ac6f72de5c97b60f35c38e9)
